name: MyToolsTown YouTube Bot

on:
  schedule:
    - cron: "*/1 * * * *"   # Runs every 30 minutes
  workflow_dispatch:          # Allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          MTT_USERNAME: ${{ secrets.MTT_USERNAME }}
          MTT_PASSWORD: ${{ secrets.MTT_PASSWORD }}
        run: python automate_mtt_youtube_bot.py
